<template>
  <div id="app">
    <!-- :class="{
      dark: darkMode,
      light: !darkMode,
    }" -->

    <div id="nav">
      <div id="homeButton">
        <router-link to="/"><i class="fas fa-home fa-2x"></i></router-link>
      </div>

      <div
        id="themeButton"
        v-on:click="
          darkMode = !darkMode;
          cssTween();
        "
      >
        <transition @enter="enter" :css="false">
          <i
            v-if="darkMode"
            key="dark"
            class="fas fa-sun fa-2x jello-horizontal"
          ></i>
          <i v-else key="light" class="fas fa-moon fa-2x"></i>
        </transition>
      </div>
    </div>
    <Navigation />
    <div class="view-wrapper">
      <router-view />
    </div>
    <Background ref="background" />
  </div>
</template>

<script>
import gsap from "gsap";
import { CSSRulePlugin } from "gsap/all";
gsap.registerPlugin(CSSRulePlugin);
import Navigation from "../src/components/Navigation";
import Background from "../src/components/Background";

export default {
  components: {
    Navigation: Navigation,
    Background: Background,
  },
  data() {
    return {
      darkMode: false,
      darkModeTween: new gsap.timeline({ paused: true }),
    };
  },
  methods: {
    cssTween() {
      var child = this.$refs.background;

      this.darkModeTween.reversed(!this.darkModeTween.reversed());
      child.animate();
    },

    // beforeEnter(el) {
    //   el.style.opacity = 0;
    //   el.style.transform = "scale(0,0)";
    // },

    enter(el, done) {
      gsap.fromTo(
        el,
        { opacity: 0, scale: 0 },
        {
          opacity: 1,
          scale: 1,
          duration: 0.7,
          ease: "back.inOut(3)",
          onComplete: done,
        }
      );
    },

    // beforeLeave(el) {
    //   el.style.opacity = 1;
    //   el.style.transform = "scale(1,1)";
    // },

    leave(el, done) {
      gsap.fromTo(
        el,
        { opacity: 1, scale: 1 },
        {
          opacity: 0,
          scale: 0,
          duration: 0.7,
          ease: "back.inOut(3)",
          onComplete: done,
        }
      );
    },
  },

  mounted() {
    // var rule = CSSRulePlugin.getRule("#app:after");
    this.darkModeTween.to(
      "html",
      1.4,
      {
        "--bg-primary": "#202326",
        ease: "power4.out",
      },
      0
    );

    this.darkModeTween.to(
      "html",
      0.5,
      { "--bg-secondary": "#823541", ease: "power4.out" },
      "<"
    );
    this.darkModeTween.to(
      "html",
      0.5,
      {
        "--text-primary": "#df485c",
        ease: "power4.out",
      },
      0
    );
    this.darkModeTween.to(
      "html",
      0.5,
      {
        "--text-secondary": "#d9d7d8",
        ease: "power4.out",
      },
      0
    );
    this.darkModeTween.reverse();
  },
};
</script>

<style lang="scss">
html,
body {
  margin: 0px !important;
  padding: 0px !important;
}

html {
  box-sizing: border-box;
  --text-primary: #202326;
  --text-secondary: #595859;
  --bg-primary: #d9d7d8;
  --bg-secondary: #c1c0c1;
  --background-image: url("../src/assets/background.svg");
  --background-image-dark: url("../src/assets/background-dark.svg");
}
*,
*:before,
*:after {
  box-sizing: inherit;
}

:root {
  font-size: 16px;
  font-family: reross-quadratic, sans-serif;
  letter-spacing: 1px;
}

#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: var(--text-primary);
  background-color: var(--bg-primary);
  min-height: 100vh;
  position: relative;
  z-index: 1;
  //width: calc(100vw - 0.25rem);
}

// #app:after {
//   //content: "";
//   opacity: 1;
//   top: 0;
//   left: 0;
//   bottom: 0;
//   right: 0;
//   position: absolute;
//   height: 100%;
//   z-index: -1;
//   background-image: var(--background-image);
//   background-position: top center;
//   background-repeat: no-repeat;
//   background-size: 100vw;
//   background-color: var(--bg-primary);
// }

#themeButton {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  padding: 0 1em;
  position: fixed;
  right: 0;
}

#homeButton {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  padding: 0 1em;
  position: fixed;
  left: 0;
}

#nav {
  padding: 1em;
  position: relative;
  z-index: 79;
  .fas:hover {
    -webkit-animation: jello-horizontal 0.9s both;
    animation: jello-horizontal 0.9s both;
  }
}

.view-wrapper {
  position: relative;
  z-index: 69;
}

a {
  text-decoration: none;
  color: var(--text-primary);

  &.router-link-exact-active {
    color: var(--text-primary);
  }
}

h1 {
  color: var(--bg-secondary);
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-8 11:51:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}

// .dark {
//   // --text-primary: #df485c;
//   // --text-secondary: #d9d7d8;
//   // --bg-primary: #202326;
//   // --bg-secondary: #823541;
//   --background-image: url("../src/assets/background-dark.svg");
// }

// .light {
//   // --text-primary: #202326;
//   // --text-secondary: #595859;
//   // --bg-primary: #d9d7d8;
//   // --bg-secondary: #c1c0c1;
//   --background-image: url("../src/assets/background.svg");
// }
</style>
